"""Runtime-installable session credential (S1-04).

S1-03's `Settings.session_token` is read once, from an environment
variable, at process construction -- adequate for the standalone entry
point, but wrong for supervised (Tauri-launched) mode: `docs/DECISIONS.md`
D-009/D-025 require the *real* session token to be generated by Tauri and
delivered to an already-running child over a private channel, strictly
after a fail-closed identity handshake (D-018) -- never via an environment
variable snapshot taken at spawn time.

`CredentialStore` is the mutable, concurrency-safe indirection that makes
that possible: `auth.py`'s middleware reads through it on every request
(from the ASGI event loop) instead of reading `Settings` directly, while a
completely different thread (the private-channel protocol reader, in
supervised mode) installs the real token into it exactly once, later, after
the D-025 challenge succeeds. Standalone mode is unaffected -- `app.py`
still pre-populates a store from `Settings.session_token` at app-creation
time, so every existing S1-03 code path and test sees identical behavior.
"""

from __future__ import annotations

import hmac
import threading

from .config import is_valid_session_token_format


class CredentialStore:
    """Holds at most one session token for this process's lifetime.

    Installation is one-time and one-time only ("Installation is one-time
    for that child instance", S1-04): once a value is installed, no later
    `install()` call -- whether a legitimate re-attempt or a confused/
    malicious message -- can replace it. This is what makes "a token from a
    previous service instance must not authenticate to a restarted
    instance" hold structurally: a *restarted* instance is a brand new
    process with a brand new, empty `CredentialStore`, and the old
    process's token was never persisted anywhere it could be replayed
    against the new one.
    """

    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._token: str | None = None
        self._installed = False

    def install(self, token: str) -> bool:
        """Installs `token` if this store is empty and `token` is
        header-safe (`config.is_valid_session_token_format`). Returns
        whether installation happened. Never raises, never logs -- an
        invalid or duplicate install attempt fails closed the same way an
        absent credential does: every request keeps being rejected.
        """
        if not is_valid_session_token_format(token):
            return False
        with self._lock:
            if self._installed:
                return False
            self._token = token
            self._installed = True
            return True

    @property
    def is_installed(self) -> bool:
        with self._lock:
            return self._installed

    def matches(self, supplied: str) -> bool:
        """Constant-time comparison against the installed token. Always
        `False` (never raises) if nothing is installed yet."""
        with self._lock:
            token = self._token
        if token is None:
            return False
        return hmac.compare_digest(supplied.encode("utf-8"), token.encode("utf-8"))

    @classmethod
    def preinstalled(cls, token: str | None) -> CredentialStore:
        """Standalone-mode convenience: a store pre-populated from a
        `Settings.session_token` value that's already known to be valid
        (or empty, if `token` is `None`/invalid) at construction time --
        preserves S1-03's exact behavior byte-for-byte."""
        store = cls()
        if token is not None:
            store.install(token)
        return store
